### PR TITLE
convert to cmake style

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by loostrum** [comment]
I can compile this successfully on ARTS, but the name of the executable has been changed to `filterbank`. Could that be changed back to `dadafilterbank`?

**Comment by jiskattema** [comment]
What happened to the compiler flags? Originally i had 
```CFLAGS += -O3 -g0 -march=native -fstrict-aliasing``` which is needed for decent performance. Will cmake pick these up from the environment during build?
Please add a note to the README on this.

**Comment by gijzelaerr** [comment]
strict-aliasing is implicitly enabled by -02 and higher. If you compile with CMAKE_BUILD_TYPE=release these are the default flags:

cc -march=native -O2 -pipe -O3 -DNDEBUG which as far as I know do what you want.

**Review by jiskattema — APPROVED** [review]
not convinced adding 'size = ' in front of the write statements is necessary.
It does not actually fix the issue that the write command could fail. (and just replaces one compiler warning with another)

**Comment by gijzelaerr** [comment]
I can't merge this myself atm.

**Comment by gijzelaerr** [comment]
btw, i don't get any compiler warnings with the current code.

**Pull request merged**
